version: '3'

volumes:
  pg_data:
  media:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: klikmok/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/var/www/kittygram
  frontend:
    env_file: .env
    image: klikmok/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/frontend_static
  gateway:
    image: klikmok/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/var/www/kittygram
